### ISSUE TITLE
Error view doesn't work properly

### ISSUE THREAD

**Issue by tmattsso** [vaadin/bookstore-example#1]
if i try to navigate to an unexisting view, I don't get this view, but i'm routed to inventory instead.

Debugged it: the problem is in SampleCrudLogic.init where it navigates to view with null; it happens to work, but also hides any errors. The other thing is that the crud view is DEFAULT with string param; any route goes to it, not the error view.

This makes it all way more difficult: https://github.com/vaadin/flow/issues/6838

**Comment by anasmi** [comment]
This was fixed by https://github.com/vaadin/flow/pull/7541
