### ISSUE TITLE
Improving the authentication mechanism in order to prevent creating SampleCrudView twice

### ISSUE THREAD

**Issue by mehdi-vaadin** [vaadin/bookstore-example#17]
When the user tries to open the inventory view (`SampleCrudView`) before he/she logins an object of the type `SampleCrudView` is created with all its dependencies including an object of the type `ProductDataProvider` and the method `MockDataService.getAllProducts` is also called. After logging in the same repeats again. 

The reason behind this is that we use BeforeEnter event of `UI` to check if a user is authenticated or not. It's in the class [BookstoreInitListener](https://github.com/vaadin/bookstore-starter-flow/blob/master/bookstore-starter-flow-ui/src/main/java/com/vaadin/samples/BookstoreInitListener.java#L22). And, the event is raised when an object of the view class has been already created. So, the solution of this problem could be moving the authentication to another point where the view is not created yet.

**Comment by mehdi-vaadin** [comment]
> This could be fixed by ["Route target instances are created before beforeEnter is called"](https://github.com/vaadin/flow/issues/4595) depending on the implementation.

The issue's been closed. This issue in Bookstore should be verified to make sure that it's fixed.

**Comment by jm-ferreira** [comment]
Upon verification this issue is fixed when using Vaadin 15.0.0.rc1. The constructor for the Inventory view and `MockDataService.getAllProducts` are being called only after login. Therefore, this issue will be closed.
