### ISSUE TITLE
Can’t navigate between views using the keyboard

### ISSUE THREAD

**Issue by jouni** [vaadin/bookstore-example#18]
The sidebar uses Tabs. Focusing the tabs and moving to the next tab using the Down/Up Arrow key and pressing the Space key selects the tab but does not navigate to the corresponding view.

While the tab is focused and you press the Tab key, you can focus the link within the tab and press the Space or Enter key to trigger the link, but that doesn’t navigate to the view either.

**Comment by anasmi** [comment]
Can't reproduce this as side menu seems to use RouterLink (`<a>`) instead. Not possible to navigate using Down/Up arrays nor reaction to press space/enter

**Comment by jouni** [comment]
Yeah, it looks like the implementation has been changed at some point to not use Tabs anymore.
