### ISSUE TITLE
App looks broken when running on production mode IE11

### ISSUE THREAD

**Issue by alvarezguille** [vaadin/bookstore-example#19]
Tested with `jetty:run` and with `package` + running tomcat both with `-Dvaadin.productionMode` and `-PproductionMode`
Dark theme is not applied, and some other styling issues as seen on the following screenshot
![image](https://user-images.githubusercontent.com/9820084/47213429-aa97b880-d3a3-11e8-9ac5-a760ec96cd1e.png)

Tested with vaadin 12.0.0.alpha4

**Comment by anasmi** [comment]
Seems to work in the latest version of starter:

<img width="845" alt="IE_Production" src="https://user-images.githubusercontent.com/15248706/72064106-db834680-32e3-11ea-8eb2-b5e80550a1c7.PNG">

**Comment by anasmi** [comment]
Closing
