### ISSUE TITLE
Update to 24.0.2

### ISSUE THREAD

**Issue by pezi** [vaadin/bookstore-example#251]
- adjust pom.xml
- exchanage javax by jakarta dependency
- TemplateRenderer replace by LitRenderer 
- replace iron elements

**Comment by pezi** [comment]
https://github.com/pezi/bookstore-example/tree/pezi/vaadin24.0.2

**Comment by mshabarov** [comment]
@pezi Bookstore has been updated to V24.1 already, so is anything still expected within this issue?

**Comment by pezi** [comment]
Problem is fixed. Sorry for not closing the issue.
